[build]
  publish = "."
  command = "echo 'Build completed'"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/products"
  to = "/admin.html"
  status = 301

[[redirects]]
  from = "/catecogry"
  to = "/admin.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/admin.html"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"