[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 301

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 301

[[redirects]]
  from = "/test"
  to = "/test_simple.html"
  status = 301

[[headers]]
  for = "*.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.php"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"