services:
  - type: web
    name: avec-amour-website
    env: static
    buildCommand: echo "Static site - no build required"
    startCommand: npx serve -s . -l $PORT
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html